# Generated by Django 3.2 on 2021-04-06 20:07

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    replaces = [
        ("tomdougiamas", "0001_initial"),
        ("tomdougiamas", "0002_blogcomment_pub_date"),
        ("tomdougiamas", "0003_auto_20210406_0837"),
        ("tomdougiamas", "0004_auto_20210406_0840"),
        ("tomdougiamas", "0005_auto_20210406_0931"),
        ("tomdougiamas", "0006_blogpost_blog_slug"),
        ("tomdougiamas", "0007_blogcomment_author"),
        ("tomdougiamas", "0008_auto_20210406_1607"),
        ("tomdougiamas", "0009_auto_20210406_1612"),
        ("tomdougiamas", "0010_auto_20210406_1615"),
        ("tomdougiamas", "0011_auto_20210406_1623"),
        ("tomdougiamas", "0012_auto_20210406_1623"),
        ("tomdougiamas", "0013_auto_20210406_1725"),
        ("tomdougiamas", "0014_alter_blogpost_blog_text"),
        ("tomdougiamas", "0015_remove_blogpost_blog_text"),
        ("tomdougiamas", "0016_blogpost_blog_text"),
        ("tomdougiamas", "0017_alter_blogcomment_pub_date"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.TextField()),
                ("pub_date", models.DateField(verbose_name="Date published")),
                ("blog_summary", models.TextField(default="")),
                ("blog_slug", models.SlugField(unique=True)),
                ("blog_text", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_text", models.TextField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tomdougiamas.blogpost",
                    ),
                ),
                (
                    "pub_date",
                    models.DateField(
                        default=datetime.datetime(
                            2021, 4, 6, 19, 15, 22, 484281, tzinfo=utc
                        ),
                        verbose_name="Date published",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
