# Generated by Django 3.1.7 on 2021-04-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="pub_date",
            field=models.DateTimeField(null=True, verbose_name="Date published"),
        ),
    ]
