# Generated by Django 3.2 on 2021-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomdougiamas", "0001_squashed_0017_alter_blogcomment_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="comment_text",
            field=models.TextField(max_length=750),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="pub_date",
            field=models.DateField(verbose_name="Date published"),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="blog_summary",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="blog_text",
            field=models.TextField(),
        ),
    ]
