# Generated by Django 3.1.7 on 2021-04-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tomdougiamas", "0002_auto_20210406_2059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
