# Generated by Django 3.2 on 2021-04-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0002_alter_blogpost_blog_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
