# Generated by Django 3.1.7 on 2021-04-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0003_auto_20210406_0837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="pub_date",
            field=models.DateField(null=True, verbose_name="Date published"),
        ),
    ]
