# Generated by Django 3.1.7 on 2021-04-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0003_auto_20210421_0308"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_title", models.TextField()),
                ("project_description", models.TextField()),
            ],
        ),
    ]
