# Generated by Django 3.2 on 2021-07-29 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0004_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.CharField(max_length=2000),
        ),
    ]
