# Generated by Django 3.1.7 on 2021-04-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0004_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_description",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_title",
            field=models.CharField(max_length=50),
        ),
    ]
