# Generated by Django 3.2.2 on 2021-08-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0004_project_project_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
