# Generated by Django 3.1.7 on 2021-04-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0004_auto_20210406_0840"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blog_summary",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="comment_text",
            field=models.TextField(max_length=500),
        ),
    ]
