# Generated by Django 3.1.7 on 2021-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0005_auto_20210406_0931"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blog_slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
