# Generated by Django 3.2.2 on 2021-08-31 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0005_auto_20210729_0321"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
