# Generated by Django 3.2 on 2021-04-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0004_auto_20210427_1137"),
        ("tomdougiamas", "0005_auto_20210422_0231"),
    ]

    operations = []
