# Generated by Django 3.1.7 on 2021-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0006_blogpost_blog_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcomment",
            name="author",
            field=models.TextField(default="admin", max_length=30),
            preserve_default=False,
        ),
    ]
