# Generated by Django 3.1.7 on 2021-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0007_blogcomment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog_slug",
            field=models.SlugField(unique=True),
        ),
    ]
