# Generated by Django 3.1.7 on 2021-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0008_auto_20210406_1607"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="author",
            field=models.CharField(max_length=30),
        ),
    ]
