# Generated by Django 3.1.7 on 2021-04-06 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tomdougiamas", "0009_auto_20210406_1612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
