# Generated by Django 3.1.7 on 2021-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0010_auto_20210406_1615"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogcomment",
            old_name="author",
            new_name="comment_author",
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="comment_text",
            field=models.TextField(max_length=200),
        ),
    ]
