# Generated by Django 3.1.7 on 2021-04-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0011_auto_20210406_1623"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogcomment",
            old_name="comment_author",
            new_name="author",
        ),
    ]
