# Generated by Django 3.2 on 2021-04-06 17:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0013_auto_20210406_1725"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="blog_text",
            field=tinymce.models.HTMLField(),
        ),
    ]
