# Generated by Django 3.2 on 2021-04-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0014_alter_blogpost_blog_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="blog_text",
        ),
    ]
