# Generated by Django 3.2 on 2021-04-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0015_remove_blogpost_blog_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="blog_text",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
