# Generated by Django 3.2 on 2021-04-06 19:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("tomdougiamas", "0016_blogpost_blog_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="pub_date",
            field=models.DateField(
                default=datetime.datetime(2021, 4, 6, 19, 15, 22, 484281, tzinfo=utc),
                verbose_name="Date published",
            ),
            preserve_default=False,
        ),
    ]
